[credentials]
emails = ["ash@encounteradelaide.com.au"] # This is just for the authenticator structure
usernames = ["alittleford"]
names = ["Ashlee Littleford"]
passwords = ["$2b$12$YAiURsplLY8WSFPBMSMDA.RI9v03Q.n2w0WpJJc2Kp3jPPwki2jBW"] # Hash for 'Encounter2025'

[cookie]
name = "HenleyPrayer"
key = "247encounter"
expiry_days = 300
