[credentials]
emails = ["ash@encounteradelaide.com.au"] # This is just for the authenticator structure
usernames = ["alittleford"]
names = ["Ashlee Littleford"]
passwords = ["$2b$12$0dJVwZrv9GlKv09gL5mg6u0s.k9ysuJcGUqTfv40ya7aR/X89997O"] # Hash for 'password123'

[cookie]
name = "HenleyPrayer"
key = "247encounter"
expiry_days = 300
