[credentials]
emails = ["ash@encounteradelaide.com.au"] # This is just for the authenticator structure
usernames = ["alittleford"]
names = ["Ashlee Littleford"]
passwords = ["b'$2b$12$2S.jdJKFv2EJGF40EWZlUOClUNWjzUsrktRTVV7oXVg0dy0KEQKKq'"] # Placeholder for 'password123'

[cookie]
name = "HenleyPrayer"
key = "247encounter"
expiry_days = 300